version: '3'

services:
  core:
    image: registry.al0.de/artpilot/ros:test
    command: /scripts/startup.sh
    volumes: 
      - ./scripts:/scripts
    devices:
      - "/dev/rpilidar:/dev/ttyUSB0"
      - "/dev/ttyS0:/dev/ttyACM0"

  # listener:
  #   build: ./
  #   environment:
  #     - "PYTHONUNBUFFERED=1"
  #   command: ros2 run demo_nodes_py listener