version: '3'

services:
  core:
    image: registry.al0.de/artpilot/ros:base
    command: roscore
    ports:
      - "11311:11311"

  # listener:
  #   build: ./
  #   environment:
  #     - "PYTHONUNBUFFERED=1"
  #   command: ros2 run demo_nodes_py listener