# production compose file
version: '3'

services:
  core:
    image: registry.al0.de/artpilot/ros:test2
    command: /scripts/startup.sh
    container_name: ros
    network_mode: host
    environment:
      - "ROS_MASTER_URI=http://192.168.100.120:11311"
      - "ROS_IP=192.168.100.120"
    extra_hosts:
      - "raspberrypi:192.168.100.120"
    volumes: 
      - ./scripts:/scripts
    devices:
      - "/dev/rpilidar:/dev/ttyUSB0"
      - "/dev/ttyS0:/dev/ttyACM0"
      - "/dev/astra_pro:/dev/astra_pro"
      - "/dev/astrauvc:/dev/astrauvc"
    restart: always

  # listener:
  #   build: ./
  #   environment:
  #     - "PYTHONUNBUFFERED=1"
  #   command: ros2 run demo_nodes_py listener
