version: '3'

services:
  core:
    image: registry.al0.de/artpilot/ros:test
    command: roscore
    ports:
      - "11311:11311"
    devices:
      - "/dev/rpilidar:/dev/ttyUSB0"
      - "/dev/ttyAMA0:/dev/serial0"


  # listener:
  #   build: ./
  #   environment:
  #     - "PYTHONUNBUFFERED=1"
  #   command: ros2 run demo_nodes_py listener