version: '3'

services:
  core:
    image: registry.al0.de/artpilot/ros:test
    command: roscore -p 11311 -v
    devices:
      - "/dev/rpilidar:/dev/ttyUSB0"
      - "/dev/ttyS0:/dev/serial0"

  # listener:
  #   build: ./
  #   environment:
  #     - "PYTHONUNBUFFERED=1"
  #   command: ros2 run demo_nodes_py listener