version: '3'

services:
  core:
    image: registry.al0.de/artpilot/ros:test2
    command: /scripts/startup.sh
    volumes: 
      - ./scripts:/scripts
    devices:
      - "/dev/rpilidar:/dev/ttyUSB0"
      - "/dev/ttyS0:/dev/ttyACM0"
      - "/dev/astra_pro:/dev/astra_pro"
      - "/dev/astrauvc:/dev/astrauvc"
    restart: unless-stopped

  # listener:
  #   build: ./
  #   environment:
  #     - "PYTHONUNBUFFERED=1"
  #   command: ros2 run demo_nodes_py listener